version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/blockloop/boar
    steps:
      - checkout
      - run: go get -u gopkg.in/alecthomas/gometalinter.v1
      - run: mv /go/bin/gometalinter.v1 /go/bin/gometalinter
      - run: gometalinter --install
      - run: gometalinter --enable-all --disable lll --disable dupl --vendor --errors
      - run: go test -v ./...
